version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fit_factor
      MYSQL_USER: fitfactor_user
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: fitfactor:create_app
      DATABASE_URL: mysql+pymysql://fitfactor_user:devpass@db:3306/fit_factor
      SECRET_KEY: somesecret
      PYTHONPATH: .
    volumes:
      - .:/app

volumes:
  db_data:


